version: "3"

vars:
  AWS_PROFILE: "{{.AWS_PROFILE}}"

tasks:
  init:
    desc: Run terraform init
    cmds:
      - terraform init

  plan:
    desc: Run terraform plan
    cmds:
      - eval "$(aws configure export-credentials --profile {{.AWS_PROFILE}} --format env)" && terraform plan

  apply:
    desc: Run terraform apply
    cmds:
      - eval "$(aws configure export-credentials --profile {{.AWS_PROFILE}} --format env)" && terraform apply

  destroy:
    desc: Run terraform destroy
    cmds:
      - eval "$(aws configure export-credentials --profile {{.AWS_PROFILE}} --format env)" && terraform destroy
